function out1 = g_rest_lengths(in1)
%G_REST_LENGTHS
%    OUT1 = G_REST_LENGTHS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Aug-2020 16:56:31

rho1 = in1(1,:);
rho2 = in1(2,:);
rho3 = in1(3,:);
rho4 = in1(4,:);
rho5 = in1(5,:);
rho6 = in1(6,:);
rho7 = in1(7,:);
rho8 = in1(8,:);
rho9 = in1(9,:);
rho10 = in1(10,:);
rho11 = in1(11,:);
rho12 = in1(12,:);
rho13 = in1(13,:);
rho14 = in1(14,:);
rho15 = in1(15,:);
rho16 = in1(16,:);
rho17 = in1(17,:);
rho18 = in1(18,:);
rho19 = in1(19,:);
rho20 = in1(20,:);
rho21 = in1(21,:);
rho22 = in1(22,:);
rho23 = in1(23,:);
rho24 = in1(24,:);
out1 = reshape([0.0,0.0,0.0,0.0,rho1,rho2,0.0,0.0,rho3,0.0,rho4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,rho5,rho6,rho7,0.0,rho8,0.0,0.0,0.0,0.0,0.0,rho9,rho10,0.0,0.0,0.0,rho11,0.0,rho12,0.0,0.0,0.0,0.0,0.0,0.0,rho13,rho14,0.0,rho15,0.0,rho16,rho1,0.0,rho9,0.0,0.0,0.0,0.0,0.0,rho17,rho18,0.0,0.0,rho2,0.0,rho10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,rho19,rho20,0.0,rho5,0.0,rho13,0.0,0.0,0.0,0.0,rho21,rho22,0.0,0.0,0.0,rho6,0.0,rho14,0.0,0.0,0.0,0.0,0.0,0.0,rho23,rho24,rho3,rho7,0.0,0.0,rho17,0.0,rho21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,rho11,rho15,rho18,0.0,rho22,0.0,0.0,0.0,0.0,0.0,rho4,rho8,0.0,0.0,0.0,rho19,0.0,rho23,0.0,0.0,0.0,0.0,0.0,0.0,rho12,rho16,0.0,rho20,0.0,rho24,0.0,0.0,0.0,0.0],[12,12]);
