function p = g_regressor__true_p_doe(in1,in2)
%G_REGRESSOR__TRUE_P_DOE
%    P = G_REGRESSOR__TRUE_P_DOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Sep-2020 16:19:19

mu1 = in1(1,:);
mu2 = in1(2,:);
mu3 = in1(3,:);
mu4 = in1(4,:);
mu5 = in1(5,:);
mu6 = in1(6,:);
mu7 = in1(7,:);
mu8 = in1(8,:);
mu9 = in1(9,:);
mu10 = in1(10,:);
mu11 = in1(11,:);
mu12 = in1(12,:);
rho1 = in2(1,:);
rho2 = in2(2,:);
rho3 = in2(3,:);
rho4 = in2(4,:);
rho5 = in2(5,:);
rho6 = in2(6,:);
rho7 = in2(7,:);
rho8 = in2(8,:);
rho9 = in2(9,:);
rho10 = in2(10,:);
rho11 = in2(11,:);
rho12 = in2(12,:);
p = [mu1.*rho1;mu2.*rho2;mu3.*rho3;mu4.*rho4;mu5.*rho5;mu6.*rho6;mu7.*rho7;mu8.*rho8;mu9.*rho9;mu10.*rho10;mu11.*rho11;mu12.*rho12;mu1;mu2;mu3;mu4;mu5;mu6;mu7;mu8;mu9;mu10;mu11;mu12];
